version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./monitoring.db
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/your_webhook_id/your_token
    volumes:
      - ./app:/app
